"""update-newspaper-subscription-t-table-add-params-column

Revision ID: 707cb0d21516
Revises: 6cc1c5bc048f
Create Date: 2024-02-29 18:58:43.025731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707cb0d21516'
down_revision = '6cc1c5bc048f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newspaper_subscription', schema=None) as batch_op:
        batch_op.add_column(sa.Column('params', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('newspaper_subscription', schema=None) as batch_op:
        batch_op.drop_column('params')

    # ### end Alembic commands ###
